---
layout: cv
title: Jayden Edmonds
---
## Business Analyst

<div id="webaddress">
  <a href="mailto:jaydenedmonds5@gmail.com">jaydenedmonds5@gmail.com</a> |
  <a href="https://www.linkedin.com/in/jayden-edmonds5/">LinkedIn</a> |
  <span>Phone: (707)-590-4271</span>
</div>


### Career Objective
Highly motivated, upcoming Business Analytics graduate 
seeking the opportunity to gather analytical experience within the industry. Eagerly ready to apply my relevant skills in the pursuit of business improvement and innovation.  

### Education
**Bachelor of Science, Business Analytics**
*Brigham Young University-Idaho*, Rexburg, ID
Anticipated Graduation: April 2025 

### Relevant Skills

- Analytical & Critical Thinking  
- Collaboration & Teamwork  
- Persuasion & Negotiation  
- Communication  
- Interpersonal  
- Adaptability  
- SQL  
- R  
- Python  
- Power BI  
- Microsoft Excel  
- Microsoft Office  

### Recent Work Experience

##### Business Analytics Intern
*OptimalShip*, Rexburg, ID  
January 2025-April 2025

- Leveraged Excel, MySQL, and Power BI to clean, organize, and analyze large datasets, ensuring accuracy while extracting actionable insights. 
- Conducted geographical, time, and predictive analyses to enhance the company's understanding of cross-border profitability, identify historical 
trends, and generate accurate forecasts for future performance. 
- Identified client behavior trends and process inefficiencies, providing recommendations for improvements. 
- Created data visualizations to present findings, enhancing decision-making processes. 

##### Mail Clerk
*BYU-Idaho Mail Services*, Rexburg, ID  
September 2022-December 2024

- Received, sorted, and delivered mail in an efficient and timely manner. 
- Prepared, processed, and documented outgoing mail pieces. 
- Coordinated with various campus departments to ensure packages were delivered or picked up most efficiently. 
- Speedily learned how to operate and leverage *SCLogic*, the logistics software used by our department in processing packages.

##### Merchandiser
*Sam’s Club*, Idaho Falls, ID  
August 2020-December 2021

- Monitored inventory levels and electronically flagged items that required restocking. 
- Arranged and showcased items in an organized and tidy manner, contributing to a positive customer shopping experience. 
- Maintained a solid work ethic and attendance record despite an early work schedule. 
- Recognized twice with the “High Five” award, for hard work and dedication.  

